package pan.tml.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-01-15T12:10:50.546+05:30
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://service.TML.PAN/", name = "dataPANStatus")
@XmlSeeAlso({ObjectFactory.class})
public interface DataPANStatus {

    @WebMethod(operationName = "PANRequest")
    @RequestWrapper(localName = "PANRequest", targetNamespace = "http://service.TML.PAN/", className = "pan.tml.service.PANRequestObject")
    @ResponseWrapper(localName = "PANResponse", targetNamespace = "http://service.TML.PAN/", className = "pan.tml.service.PANResponseObject")
    public void panRequest(
        @WebParam(name = "docType", targetNamespace = "")
        java.lang.String docType,
        @WebParam(name = "consent", targetNamespace = "")
        java.lang.String consent,
        @WebParam(name = "pan", targetNamespace = "")
        java.lang.String pan,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(mode = WebParam.Mode.OUT, name = "status_code", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> statusCode,
        @WebParam(mode = WebParam.Mode.OUT, name = "request_id", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> requestId,
        @WebParam(mode = WebParam.Mode.OUT, name = "PANresult", targetNamespace = "")
        javax.xml.ws.Holder<ResultPANObject> paNresult,
        @WebParam(mode = WebParam.Mode.OUT, name = "Nameresult", targetNamespace = "")
        javax.xml.ws.Holder<ResultNameObject> nameresult
    );
}
