kind: 'BuildConfig'
apiVersion: 'v1'
metadata:
  name: 'ekycpanstatus'
  namespace: cicd
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/chaitalittl/eKYC_TML_PANStatus.git'
    sourceSecret:
      name: github-ekyc-pan  
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: PROJECT
        value: dev
      jenkinsfilePath: 'Jenkinsfile'